### ISSUE TITLE
Publish APK on Github?

### ISSUE THREAD

**Issue by IzzySoft** [GrenderG/Tappic#1]
Would you mind publishing the `.apk` here at Github – for those unable or unwilling to use GPlay? Thanks in advance!

**Comment by GrenderG** [comment]
Here it is: [https://github.com/GrenderG/Tappic/releases/download/1.5/Tappic-v1.5.apk](https://github.com/GrenderG/Tappic/releases/download/1.5/Tappic-v1.5.apk)

**Comment by IzzySoft** [comment]
Wow – that was fast, thanks a million! Now folks with an F-Droid client can grab it [here](https://apt.izzysoft.de/fdroid/index/apk/es.dmoral.tappic), and receive updates automatically :) Also to be found [in my app listings](https://android.izzysoft.de/applists/category/named/foto_galleries#group_200).

Just a note: [On VT](https://www.virustotal.com/de/file/2fae8946162acc166925da9823a361fcd54a0dc30812813bfbcf49ac015668ce/analysis/1480545697/), one engine reports "bad contents". False alert IMHO, but just to let you know. I'll schedule a rescan tomorrow to see if updated signatures have fixed that (usually that's the case).

Oh, guess we can close this issue then? :smiley_cat:

**Comment by GrenderG** [comment]
Thanks a lot. That's so weird, gonna recompile it or something, don't know what's happening.

**EDIT: I have recompiled the app, then uploaded it again and now that report is gone as you can see [here](https://www.virustotal.com/de/file/28c585a2818be731c079aa2ef3e176c1cb73534c2563913d471b777d1f7ec0d0/analysis/1482367345/).
The link for the app is the same, just [click here](https://github.com/GrenderG/Tappic/releases/download/1.5/Tappic-v1.5.apk).**

All right, then? :smile:

**Comment by IzzySoft** [comment]
That's good news! I've just replaced the file and ran an update on the database – all clean now, [as you can see](https://apt.izzysoft.de/fdroid/index/apk/es.dmoral.tappic) :smiley_cat: 

Thanks a lot again!

**Comment by GrenderG** [comment]
Thanks for your time, closing this now!
