### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by IzzySoft** [GrenderG/Tappic#3]
As there was no commit for about 2 years: is this project still maintained?

**Comment by GrenderG** [comment]
I'm open to suggestions about how to improve it. :stuck_out_tongue:

**Comment by IzzySoft** [comment]
Thanks, that answers my question: you've not abandoned this project :smiley:

If you wonder for the background of my question: I was just doing my "annually inventory" for my F-Droid repo. Dont want users to be disappointed with having them installing apps that are no longer maintained – without them being aware of that fact (which I then include with the app's description). So I checked with all projects not having had any commits for 2 years or more.

And there was [your app](https://apt.izzysoft.de/fdroid/index/apk/es.dmoral.tappic), so I checked up with you. If you want the description updated, let me know :wink:

**Comment by GrenderG** [comment]
It's ok, don't worry and thanks for asking!

**Comment by IzzySoft** [comment]
Just wondering (as I received reports the app is no longer working on Android 14 – and probably neither non 12/13), should we declare the app "sunset"? And should it still be kept at IzzyOnDroid – or would you say there are sufficient suitable alternatives?
